// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjcMVYtr1Pkw36zBgFHqgosqvo4VGm_m8',
    appId: '1:960877383229:web:f09bddd9be2335977c6454',
    messagingSenderId: '960877383229',
    projectId: 'app-flutter-flordeluna',
    authDomain: 'app-flutter-flordeluna.firebaseapp.com',
    storageBucket: 'app-flutter-flordeluna.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqiwM8yqWs1GqYkedJJtDz7fWzt-2qyA',
    appId: '1:960877383229:android:0086ae65b8d6bb727c6454',
    messagingSenderId: '960877383229',
    projectId: 'app-flutter-flordeluna',
    storageBucket: 'app-flutter-flordeluna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsASRPm-tb-PGnQ1vSAL1-gYV2lCI4Q0',
    appId: '1:960877383229:ios:e2bb165548caaf9f7c6454',
    messagingSenderId: '960877383229',
    projectId: 'app-flutter-flordeluna',
    storageBucket: 'app-flutter-flordeluna.firebasestorage.app',
    iosBundleId: 'com.example.florDeLuna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjcMVYtr1Pkw36zBgFHqgosqvo4VGm_m8',
    appId: '1:960877383229:web:bd8afebb75559dfa7c6454',
    messagingSenderId: '960877383229',
    projectId: 'app-flutter-flordeluna',
    authDomain: 'app-flutter-flordeluna.firebaseapp.com',
    storageBucket: 'app-flutter-flordeluna.firebasestorage.app',
  );
}
